-- ============================================================
-- Ecosystem - development seed data
--
-- Mirrors lib/data/demo_bins.dart and lib/screens/demo_data.dart so the
-- database and the Flutter demo mode show the same network.
--
-- Run AFTER schema.sql:   psql -d ecosystem -f seed.sql
--
-- Every insert is idempotent (ON CONFLICT DO NOTHING) and every UUID is
-- fixed, so re-running this never duplicates rows.
--
-- Passwords are deliberately NULL. Seed accounts cannot be logged into
-- until a real Argon2id hash is generated by the (not yet written) auth
-- service. Do not commit a working password hash to a shared database.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Users
-- ------------------------------------------------------------

INSERT INTO users (id, name, nickname, phone, avatar_icon, role_id, ambassador_state, ambassador_area, ambassador_motivation, ambassador_applied_at)
VALUES
    ('00000000-0000-4000-8000-000000000001', 'System',    'Admin',   '+233200000001', U&'\+01F6E1\FE0F', 'admin',      'none', NULL, NULL, NULL),
    ('00000000-0000-4000-8000-000000000002', 'Ama Boateng', 'Ama',   '+233200000002', U&'\+01F333', 'ambassador', 'approved', 'Market Square', 'Wanted to keep the market clean on collection days.', now() - interval '60 days'),
    ('00000000-0000-4000-8000-000000000003', 'Kofi Mensah', 'Kofi',  '+233200000003', U&'\+01F6B2', 'ambassador', 'approved', 'North Campus',  'Students near the hostels were overflowing bins weekly.', now() - interval '45 days'),
    ('00000000-0000-4000-8000-000000000010', 'Kwame Owusu',  'Kweku',  '+233200000010', U&'26BD', 'user',       'none', NULL, NULL, NULL),
    ('00000000-0000-4000-8000-000000000011', 'Abena Sarpong','Abena',  '+233200000011', U&'\+01F4DA', 'user',       'none', NULL, NULL, NULL),
    ('00000000-0000-4000-8000-000000000012', 'Yaw Darko',    'Yaw',    '+233200000012', U&'\+01F3A7', 'user',       'pending', 'Ring Road East', 'I see the junction bins fill up every weekend.', now() - interval '2 days')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- Bins
--
-- BIN-001..BIN-006 match demo_bins.dart exactly, including the
-- created_by ids that were missing there (demo mode showed "my bins: 0").
-- ------------------------------------------------------------

INSERT INTO bins (id, code, name, bin_state, status_source, fill_percent, capacity_kg, address, latitude, longitude, sensor_id, created_by_id, created_by_role)
VALUES
    ('10000000-0000-4000-8000-000000000001', 'BIN-001', 'Campus Main Gate',  'available', 'sensor',  22.00, 120, 'Main Gate, University Road',        5.6042000, -0.1875000, 'SNS-1001', '00000000-0000-4000-8000-000000000001', 'admin'),
    ('10000000-0000-4000-8000-000000000002', 'BIN-002', 'Library Car Park',  'filling',   'sensor',  64.00, 120, 'Library Car Park, Block C',          5.6071000, -0.1841000, 'SNS-1002', '00000000-0000-4000-8000-000000000001', 'admin'),
    ('10000000-0000-4000-8000-000000000003', 'BIN-003', 'Market Square',     'full',      'sensor',  98.00,  80, 'Market Square, Central',             5.5998000, -0.1908000, 'SNS-1003', '00000000-0000-4000-8000-000000000002', 'ambassador'),
    ('10000000-0000-4000-8000-000000000004', 'BIN-004', 'Hostel Block A',    'available', 'manual',  31.00, 120, 'Hostel Block A, North Campus',       5.6092000, -0.1921000, NULL,       '00000000-0000-4000-8000-000000000003', 'ambassador'),
    ('10000000-0000-4000-8000-000000000005', 'BIN-005', 'Junction Traffic',  'full',      'manual', 100.00, 120, 'Junction, Ring Road East',           5.5956000, -0.1838000, NULL,       '00000000-0000-4000-8000-000000000002', 'ambassador'),
    ('10000000-0000-4000-8000-000000000006', 'BIN-006', 'Community Centre',  'disabled',  'sensor',  45.00,  60, 'Community Centre, West',             5.6117000, -0.1855000, 'SNS-1006', '00000000-0000-4000-8000-000000000001', 'admin')
ON CONFLICT (id) DO NOTHING;

ALTER SEQUENCE bin_code_seq RESTART WITH 7;

UPDATE bins
SET notes = 'Lid hinge replaced, awaiting re-test.'
WHERE id = '10000000-0000-4000-8000-000000000006'
  AND notes IS DISTINCT FROM 'Lid hinge replaced, awaiting re-test.';

-- Backfill the history table so bin_status_events is not empty on a fresh
-- database. Seeded directly rather than via UPDATE, because the
-- bins_log_state_change trigger only fires on UPDATE.
INSERT INTO bin_status_events (bin_id, previous_state, new_state, fill_percent, source, reported_by_id, note)
SELECT
    id,
    NULL,
    bin_state,
    fill_percent,
    status_source,
    created_by_id,
    'Imported from legacy Firebase collection'
FROM bins
WHERE NOT EXISTS (
    SELECT 1 FROM bin_status_events e WHERE e.bin_id = bins.id
);

-- ------------------------------------------------------------
-- RFID cards
-- ------------------------------------------------------------

INSERT INTO rfid_cards (id, tag_raw, tag_normalised, tag_length, card_kind, state, assigned_user_id, issued_by)
VALUES
    ('20000000-0000-4000-8000-000000000001', 'a3f9:21c0',   'A3F9 21C0',   8, 'em4100',   'linked', '00000000-0000-4000-8000-000000000010', '00000000-0000-4000-8000-000000000001'),
    ('20000000-0000-4000-8000-000000000002', '7B2E9A10',    '7B2E 9A10',   8, 'em4100',   'linked', '00000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-000000000001'),
    ('20000000-0000-4000-8000-000000000003', '04FF1C9D2233', '04FF 1C9D 2233', 12, 'mifare_1k', 'available', NULL, NULL),
    ('20000000-0000-4000-8000-000000000004', '11AA22BB',    '11AA 22BB',   8, 'student_id', 'available', NULL, NULL),
    ('20000000-0000-4000-8000-000000000005', '9901FE04',    '9901 FE04',   8, 'em4100',   'lost',   NULL, NULL)
ON CONFLICT (id) DO NOTHING;

UPDATE rfid_cards
SET lost_at = now() - interval '10 days'
WHERE id = '20000000-0000-4000-8000-000000000005'
  AND lost_at IS NULL;

-- ------------------------------------------------------------
-- Rewards
-- ------------------------------------------------------------

INSERT INTO rewards (id, title, partner_name, cost_points, stock)
VALUES
    ('30000000-0000-4000-8000-000000000001', '10% off at Campus Canteen', 'Campus Canteen',  150,  50),
    ('30000000-0000-4000-8000-000000000002', 'Reusable Water Bottle',      'Boame',           400,  20),
    ('30000000-0000-4000-8000-000000000003', 'T-Shirt (Eco Edition)',      'Boame',           900,  10),
    ('30000000-0000-4000-8000-000000000004', 'School Fee Credit',          'Scholarship Fund', 2000, NULL)
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- Deposits
--
-- Users are seeded with zero totals on purpose. The deposits_apply_totals
-- trigger recalculates points/bottles/weight, so running this file proves
-- the trigger works instead of asserting a number that may drift.
-- ------------------------------------------------------------

INSERT INTO deposits (id, user_id, bin_id, bottle_kind, bottle_count, weight_kg, points_awarded, reference_code)
VALUES
    ('40000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000001', 'clear',   12, 0.420, 60,  'DEP-DEMO-0001'),
    ('40000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000004', 'coloured',  8, 0.360, 40,  'DEP-DEMO-0002'),
    ('40000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000002', 'clear',   20, 0.700, 100, 'DEP-DEMO-0003'),
    ('40000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000002', 'coloured',  6, 0.270, 30,  'DEP-DEMO-0004'),
    ('40000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000012', '10000000-0000-4000-8000-000000000003', 'clear',   15, 0.525, 75,  'DEP-DEMO-0005')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- Collections
-- ------------------------------------------------------------

INSERT INTO collections (id, bin_id, collected_by_id, weight_kg, is_estimated, notes, collected_at)
VALUES
    ('50000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000002', 78.40, false, 'Full skip emptied.', now() - interval '3 days'),
    ('50000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000002', 61.00, true,  'Weighed by hand at the junction.', now() - interval '1 day')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- Redemptions, messages, notifications
-- These are the three queues the Firebase version had nowhere to read.
-- ------------------------------------------------------------

INSERT INTO redemptions (id, user_id, reward_id, cost_points, status)
VALUES
    ('60000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000010', '30000000-0000-4000-8000-000000000001', 150, 'pending'),
    ('60000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000011', '30000000-0000-4000-8000-000000000002', 400, 'pending'),
    ('60000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000012', '30000000-0000-4000-8000-000000000003', 900, 'rejected')
ON CONFLICT (id) DO NOTHING;

UPDATE redemptions
SET review_note = 'Not enough points in stock this cycle.'
WHERE id = '60000000-0000-4000-8000-000000000003'
  AND review_note IS NULL;

INSERT INTO contact_messages (id, user_id, name, email, message)
VALUES
    ('70000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000011', 'Abena Sarpong', 'abena@example.test',
     'The RFID reader at the Library Car Park kiosk is not detecting my card. It worked last week.'),
    ('70000000-0000-4000-8000-000000000002', NULL, 'Accra Waste Company', 'waste@example.test',
     'We would like to sponsor two bins on the Ring Road. Who do we speak to?')
ON CONFLICT (id) DO NOTHING;

INSERT INTO notifications (id, user_id, title, body, kind)
VALUES
    ('80000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000010', 'Bin full near you', 'Community Centre is full and awaiting collection.', 'bin'),
    ('80000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000011', 'Redemption approved', 'Your campus canteen voucher is ready to collect.', 'reward')
ON CONFLICT (id) DO NOTHING;

INSERT INTO audit_log (actor_id, action, entity_type, entity_id, details)
VALUES
    ('00000000-0000-4000-8000-000000000001', 'role.changed', 'user', '00000000-0000-4000-8000-000000000002',
     '{"from":"user","to":"ambassador"}'::jsonb),
    ('00000000-0000-4000-8000-000000000001', 'bin.disabled', 'bin', '10000000-0000-4000-8000-000000000006',
     '{"reason":"Lid hinge replaced"}'::jsonb);

COMMIT;
