// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATR4Ygz6OJWhIkwn5qkc5d1VTf5gGco-Q',
    appId: '1:717947169542:ios:44bf2356e1da0451bb8c87',
    messagingSenderId: '717947169542',
    projectId: 'sandra-c4bd7',
    databaseURL: 'https://sandra-c4bd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandra-c4bd7.firebasestorage.app',
    iosBundleId: 'com.example.ecosytem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP94UVCbdNMnKMjMIiP9qk8lZY1N6Z78M',
    appId: '1:717947169542:web:5ffb3a98b6694d71bb8c87',
    messagingSenderId: '717947169542',
    projectId: 'sandra-c4bd7',
    authDomain: 'sandra-c4bd7.firebaseapp.com',
    databaseURL: 'https://sandra-c4bd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandra-c4bd7.firebasestorage.app',
    measurementId: 'G-3J3ZEPQEEC',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP94UVCbdNMnKMjMIiP9qk8lZY1N6Z78M',
    appId: '1:717947169542:web:5ffb3a98b6694d71bb8c87',
    messagingSenderId: '717947169542',
    projectId: 'sandra-c4bd7',
    authDomain: 'sandra-c4bd7.firebaseapp.com',
    databaseURL: 'https://sandra-c4bd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandra-c4bd7.firebasestorage.app',
    measurementId: 'G-3J3ZEPQEEC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATR4Ygz6OJWhIkwn5qkc5d1VTf5gGco-Q',
    appId: '1:717947169542:ios:44bf2356e1da0451bb8c87',
    messagingSenderId: '717947169542',
    projectId: 'sandra-c4bd7',
    databaseURL: 'https://sandra-c4bd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandra-c4bd7.firebasestorage.app',
    iosBundleId: 'com.example.ecosytem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFXOmgj5d17ys9GwQ4ubvI_BnaxFjXG8',
    appId: '1:717947169542:android:cca6bd486cc7dba7bb8c87',
    messagingSenderId: '717947169542',
    projectId: 'sandra-c4bd7',
    databaseURL: 'https://sandra-c4bd7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandra-c4bd7.firebasestorage.app',
  );
}
